/*
 * ProcessColumnChoose.java
 *
 * Created on __DATE__, __TIME__
 */

package com.jida.gui;

/**
 *
 * @author  __USER__
 */
public class ProcessColumnChoose extends javax.swing.JFrame {

	/** Creates new form ProcessColumnChoose */
	public ProcessColumnChoose() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		ckCustName = new javax.swing.JCheckBox();
		ckProvince = new javax.swing.JCheckBox();
		ckProductName = new javax.swing.JCheckBox();
		ckType = new javax.swing.JCheckBox();
		ckPosNo = new javax.swing.JCheckBox();
		ckProcessDate = new javax.swing.JCheckBox();
		ckProcessNo = new javax.swing.JCheckBox();
		ckNum = new javax.swing.JCheckBox();
		ckUnitPrice = new javax.swing.JCheckBox();
		ckTotalPrice = new javax.swing.JCheckBox();
		ckInvoiceNo = new javax.swing.JCheckBox();
		ckTransportNo = new javax.swing.JCheckBox();
		ckLinkman = new javax.swing.JCheckBox();
		ckEmployee = new javax.swing.JCheckBox();
		ckMemo = new javax.swing.JCheckBox();
		ckProcessID = new javax.swing.JCheckBox();
		btnCancel = new javax.swing.JButton();
		btnOK = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		ckCustName.setText("\u5ba2\u6237\u540d");
		ckCustName.setEnabled(false);

		ckProvince.setText("\u7701\u4efd");

		ckProductName.setText("\u540d\u79f0");

		ckType.setText("\u578b\u53f7");

		ckPosNo.setText("\u4f4d\u53f7");

		ckProcessDate.setText("\u52a0\u5de5\u65e5\u671f");

		ckProcessNo.setText("\u5408\u540c\u53f7");

		ckNum.setText("\u6570\u91cf");

		ckUnitPrice.setText("\u5355\u4ef7");

		ckTotalPrice.setText("\u603b\u4ef7");

		ckInvoiceNo.setText("\u53d1\u7968\u7f16\u53f7");

		ckTransportNo.setText("\u8fd0\u8f93\u7f16\u53f7");

		ckLinkman.setText("\u8054\u7cfb\u4eba");

		ckEmployee.setText("\u4e1a\u52a1\u5458");

		ckMemo.setText("\u5907\u6ce8");

		ckProcessID.setText("\u52a0\u5de5ID");
		ckProcessID.setEnabled(false);

		btnCancel.setText("\u53d6\u6d88");
		btnCancel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCancelActionPerformed(evt);
			}
		});

		btnOK.setText("\u786e\u5b9a");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																ckCustName)
														.addComponent(
																ckProvince)
														.addComponent(
																ckProductName)
														.addComponent(ckType)
														.addComponent(ckPosNo)
														.addComponent(
																ckProcessDate))
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																ckProcessNo)
														.addComponent(ckNum)
														.addComponent(
																ckUnitPrice)
														.addComponent(
																ckTotalPrice)
														.addComponent(
																ckInvoiceNo)
														.addComponent(
																ckTransportNo))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(ckLinkman)
														.addComponent(
																ckEmployee)
														.addComponent(ckMemo)
														.addComponent(
																ckProcessID))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addContainerGap(85, Short.MAX_VALUE)
										.addComponent(btnOK)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(btnCancel)
										.addContainerGap()));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																ckCustName)
														.addComponent(
																ckProcessNo)
														.addComponent(ckLinkman))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																ckProvince)
														.addComponent(ckNum)
														.addComponent(
																ckEmployee))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																ckProductName)
														.addComponent(
																ckUnitPrice)
														.addComponent(ckMemo))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(ckType)
														.addComponent(
																ckTotalPrice)
														.addComponent(
																ckProcessID))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(ckPosNo)
														.addComponent(
																ckInvoiceNo))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																ckProcessDate)
														.addComponent(
																ckTransportNo))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(btnCancel)
														.addComponent(btnOK))
										.addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {
		this.dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ProcessColumnChoose().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnCancel;
	private javax.swing.JButton btnOK;
	private javax.swing.JCheckBox ckCustName;
	private javax.swing.JCheckBox ckEmployee;
	private javax.swing.JCheckBox ckInvoiceNo;
	private javax.swing.JCheckBox ckLinkman;
	private javax.swing.JCheckBox ckMemo;
	private javax.swing.JCheckBox ckNum;
	private javax.swing.JCheckBox ckPosNo;
	private javax.swing.JCheckBox ckProcessDate;
	private javax.swing.JCheckBox ckProcessID;
	private javax.swing.JCheckBox ckProcessNo;
	private javax.swing.JCheckBox ckProductName;
	private javax.swing.JCheckBox ckProvince;
	private javax.swing.JCheckBox ckTotalPrice;
	private javax.swing.JCheckBox ckTransportNo;
	private javax.swing.JCheckBox ckType;
	private javax.swing.JCheckBox ckUnitPrice;
//	private javax.swing.JCheckBox[] cks = new javax.swing.JCheckBox[] {
//			ckCustName, ckProvince, ckProductName, ckType, ckPosNo,
//			ckProcessDate, ckProcessNo, ck
//	};
	// End of variables declaration//GEN-END:variables

}