/*
 * UserInfo.java
 *
 * Created on __DATE__, __TIME__
 */

package com.jida.gui;

import javax.swing.JOptionPane;

import com.jida.MvcProperties;
import com.jida.user.AuthSession;
import com.jida.user.domObject.User;

/**
 *
 * @author  __USER__
 */
public class UserInfo extends javax.swing.JDialog {

	private static final long serialVersionUID = 1L;
	/** Creates new form UserInfo */
	public UserInfo(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		imageLabel = new javax.swing.JLabel();
		titleLabel = new javax.swing.JLabel();
		nameLabel = new javax.swing.JLabel();
		levelLabel = new javax.swing.JLabel();
		nameItem = new javax.swing.JLabel();
		levelItem = new javax.swing.JLabel();
		btnOK = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		imageLabel
				.setIcon(new javax.swing.ImageIcon(
						"images/Slayman.png")); // NOI18N

		titleLabel.setFont(new java.awt.Font("宋体", 1, 14));
		titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		titleLabel.setText("\u7528\u6237\u4fe1\u606f");

		nameLabel.setFont(new java.awt.Font("宋体", 1, 12));
		nameLabel.setText("\u7528\u6237\u540d\uff1a");

		levelLabel.setFont(new java.awt.Font("宋体", 1, 12));
		levelLabel.setText("用户信息");

		nameItem.setText("\u7528\u6237\u540d");

		levelItem.setText("\u7528\u6237\u7ea7\u522b");

		btnOK.setText("\u786e\u5b9a");
		btnOK.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnOKActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(imageLabel)
										.addGap(18, 18, 18)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																levelLabel,
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																nameLabel,
																javax.swing.GroupLayout.Alignment.TRAILING))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																levelItem,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																231,
																Short.MAX_VALUE)
														.addComponent(
																nameItem,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																231,
																Short.MAX_VALUE))
										.addContainerGap()).addGroup(
								layout.createSequentialGroup().addGap(78, 78,
										78).addComponent(titleLabel,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										302, Short.MAX_VALUE)
										.addGap(12, 12, 12)).addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup().addContainerGap(
										343, Short.MAX_VALUE).addComponent(
										btnOK).addContainerGap()));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				titleLabel)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								nameLabel)
																						.addComponent(
																								nameItem)))
														.addComponent(imageLabel))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(levelLabel)
														.addComponent(levelItem))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE).addComponent(
												btnOK).addContainerGap()));

		pack();
		this.initInfo();
	}// </editor-fold>
	//GEN-END:initComponents

	private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {
		dispose();
	}

	private void setUserName(String name) {
		this.nameItem.setText(name);
	}

	private void setUserLevel(String level) {
		this.levelItem.setText(level);
	}

	private void initInfo() {
		AuthSession as = AuthSession.getInstance();
		if(!as.isSessionActive()) {
			JOptionPane.showMessageDialog(this, "您还没有登录", "快登陆呀", JOptionPane.ERROR_MESSAGE);
			this.dispose();
			System.exit(9009);
		}
		User u = as.getUser();
		this.setUserName(u.getName());
		this.setUserLevel(u.getMobile()+","+u.getTel()+","+u.getAddr());
//		switch(u.getType()) {
//		case User.ADMIN:
//			this.setUserLevel(MvcProperties.USER_LVL_ADMIN_DESC);
//			break;
//		case User.OPERATOR:
//			this.setUserLevel(MvcProperties.USER_LVL_OPERATOR_DESC);
//			break;
//		case User.ANONYMOUS_VISITOR:
//			this.setUserLevel(MvcProperties.USER_LVL_VISITOR_DESC);
//			break;
//		default:
//			return;
//		}

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				UserInfo dialog = new UserInfo(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnOK;
	private javax.swing.JLabel imageLabel;
	private javax.swing.JLabel titleLabel;
	private javax.swing.JLabel nameLabel;
	private javax.swing.JLabel levelLabel;
	private javax.swing.JLabel nameItem;
	private javax.swing.JLabel levelItem;
	// End of variables declaration//GEN-END:variables

}